import Head from 'next/head'
import Products from '../components/Products'
import { FaShippingFast, FaExchangeAlt, FaCreditCard } from "react-icons/fa";

export async function getStaticProps (){
  const response = await fetch('https://fakestoreapi.com/products');
  const data = await response.json();

  if (!data) {
      return {
        notFound: true,
      }
  }

  return {
      props: { data },
  }
}

export default function Home({ data }) {
  
  return (
    <div>
      <Head>
        <title>E-commerce store</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <header className="w-full h-screen grid">
        <div className="bg-hero-img bg-no-repeat bg-center bg-cover w-full h-full flex justify-center items-center overflow-hidden">
          <h1 className=" text-gray-100 text-5xl md:text-9xl">Le Stylist</h1>
        </div>
      </header>
      <main className="my-16">
        <div className="relative ">
          <h1 className="opacity-20 text-5xl lg:text-9xl text-center">TRENDING</h1>
          <h3 className="absolute top-4 lg:top-14 lg:text-4xl w-full text-center">TRENDING</h3>
        </div>
        <Products data={data} />
        <div className="bg-summer-img bg-no-repeat bg-center bg-cover w-full h-screen mt-16 flex justify-center items-center">
          <h1 className="text-white text-6xl md:text-8xl font-extrabold">SUMMER SALE</h1>
        </div>
        <div className="bg-gray-100">
          <div className=" flex flex-col md:flex-row justify-between md:mx-16 lg:mx-28 lg:py-36">
            <div className="h-40 flex flex-col justify-center items-center">
              <FaExchangeAlt className="text-4xl md:text-6xl mb-6 text-gray-900"/>
              <h4 className="text-2xl text-gray-900">REFUND POLICY</h4>
            </div>
            <div className="h-40 flex flex-col justify-center items-center">
              <FaCreditCard className="text-4xl md:text-6xl mb-6 text-gray-900"/>
              <h4 className="text-2xl text-gray-900">SECURE PAYMENTS</h4>
            </div>
            <div className="h-40 flex flex-col justify-center items-center">
              <FaShippingFast className="text-4xl md:text-6xl mb-6 text-gray-900"/>
              <h4 className="text-2xl text-gray-900">FREE SHIPPING</h4>
            </div>
          </div>
        </div>
        <div className="relative mt-12 mx-6">
          <h1 className="opacity-10 text-5xl lg:text-9xl text-center">Subscribe</h1>
          <h3 className="absolute top-4 lg:top-14 lg:text-4xl w-full text-center">Subscribe to our Newsletter</h3>
          <form className="flex justify-center items-center mt-16">
            <input type="text" name="newsletter" placeholder="Email Address" className="py-3 w-72 border-black focus:border-black focus:ring-transparent focus:outline-none"></input>
            <input type="submit" name="submit" className="py-3 w-28 bg-black text-white border cursor-pointer border-black px-4"></input>
          </form>
        </div>
      </main>
    </div>
  )
}
